# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DKOM 2021"
email: "pavan.s@sap.com"
description: "DKOM 2021"
baseurl: "/zeppelin"
url: "https://kesavanking.github.io/"



# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}


heroImage: "hero.jpg"
heroTitle: "SAP DKOM India <typeout> 2021"
eventDate: "January 22, 2021"
typeoutTextValues: '"", "Season","India"'
typeoutFallback: "Season"
heroButtons:
 - {permalink: "/#tickets", text: "Session Schedule"}
 - {permalink: "/#tickets", text: "Hands-On Lab"}